#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := camera_example

EXTRA_COMPONENT_DIRS := /home/edev/esp/esp32-camera

include $(IDF_PATH)/make/project.mk

